//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace FluorineFx {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    var temp = new ResourceManager("FluorineFx.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin AMF request.
        /// </summary>
        internal static string Amf_Begin {
            get {
                return ResourceManager.GetString("Amf_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End AMF request.
        /// </summary>
        internal static string Amf_End {
            get {
                return ResourceManager.GetString("Amf_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amf message was not handled. Check your log file for further information.
        /// </summary>
        internal static string Amf_Fatal {
            get {
                return ResourceManager.GetString("Amf_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Failed to handle AMF message. Check your log file for further information.
        /// </summary>
        internal static string Amf_Fatal404 {
            get {
                return ResourceManager.GetString("Amf_Fatal404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadBody failed.
        /// </summary>
        internal static string Amf_ReadBodyFail {
            get {
                return ResourceManager.GetString("Amf_ReadBodyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send an error response.
        /// </summary>
        internal static string Amf_ResponseFail {
            get {
                return ResourceManager.GetString("Amf_ResponseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amf message serializer failed.
        /// </summary>
        internal static string Amf_SerializationFail {
            get {
                return ResourceManager.GetString("Amf_SerializationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppConnect: {0}.
        /// </summary>
        internal static string AppAdapter_AppConnect {
            get {
                return ResourceManager.GetString("AppAdapter_AppConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppDisconnect: {0}.
        /// </summary>
        internal static string AppAdapter_AppDisconnect {
            get {
                return ResourceManager.GetString("AppAdapter_AppDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppJoin: {0} &gt;&gt; {1}.
        /// </summary>
        internal static string AppAdapter_AppJoin {
            get {
                return ResourceManager.GetString("AppAdapter_AppJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppLeave: {0} &lt;&lt; {1}.
        /// </summary>
        internal static string AppAdapter_AppLeave {
            get {
                return ResourceManager.GetString("AppAdapter_AppLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppStart: {0}.
        /// </summary>
        internal static string AppAdapter_AppStart {
            get {
                return ResourceManager.GetString("AppAdapter_AppStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppStop: {0}.
        /// </summary>
        internal static string AppAdapter_AppStop {
            get {
                return ResourceManager.GetString("AppAdapter_AppStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomConnect: {0}.
        /// </summary>
        internal static string AppAdapter_RoomConnect {
            get {
                return ResourceManager.GetString("AppAdapter_RoomConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomDisconnect: {0}.
        /// </summary>
        internal static string AppAdapter_RoomDisconnect {
            get {
                return ResourceManager.GetString("AppAdapter_RoomDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomJoin: {0} &gt;&gt; {1}.
        /// </summary>
        internal static string AppAdapter_RoomJoin {
            get {
                return ResourceManager.GetString("AppAdapter_RoomJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomLeave: {0} &lt;&lt; {1}.
        /// </summary>
        internal static string AppAdapter_RoomLeave {
            get {
                return ResourceManager.GetString("AppAdapter_RoomLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomStart: {0}.
        /// </summary>
        internal static string AppAdapter_RoomStart {
            get {
                return ResourceManager.GetString("AppAdapter_RoomStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomStop: {0}.
        /// </summary>
        internal static string AppAdapter_RoomStop {
            get {
                return ResourceManager.GetString("AppAdapter_RoomStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the passed arguments does not meet the parameter specification of the called method. {0} parameters for method {1}, expecting {2}.
        /// </summary>
        internal static string Arg_Mismatch {
            get {
                return ResourceManager.GetString("Arg_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to the request {0} retrieved from cache.
        /// </summary>
        internal static string Cache_Hit {
            get {
                return ResourceManager.GetString("Cache_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to the request {0} retrieved from cache with key {1} .
        /// </summary>
        internal static string Cache_HitKey {
            get {
                return ResourceManager.GetString("Cache_HitKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rtmp channel not found.
        /// </summary>
        internal static string Channel_NotFound {
            get {
                return ResourceManager.GetString("Channel_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class definition {0} loaded.
        /// </summary>
        internal static string ClassDefinition_Loaded {
            get {
                return ResourceManager.GetString("ClassDefinition_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class definition (untyped) loaded.
        /// </summary>
        internal static string ClassDefinition_LoadedUntyped {
            get {
                return ResourceManager.GetString("ClassDefinition_LoadedUntyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new client with id {0}.
        /// </summary>
        internal static string Client_Create {
            get {
                return ResourceManager.GetString("Client_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client with id {0} has been invalidated.
        /// </summary>
        internal static string Client_Invalidated {
            get {
                return ResourceManager.GetString("Client_Invalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client with id {0} changing lease time from {1} to {2}.
        /// </summary>
        internal static string Client_Lease {
            get {
                return ResourceManager.GetString("Client_Lease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientManager cache expired, client with id {0}.
        /// </summary>
        internal static string ClientManager_CacheExpired {
            get {
                return ResourceManager.GetString("ClientManager_CacheExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientManager removing client with id {0}.
        /// </summary>
        internal static string ClientManager_Remove {
            get {
                return ResourceManager.GetString("ClientManager_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line:{0}, Column:{1} Message:{2}.
        /// </summary>
        internal static string Compiler_Error {
            get {
                return ResourceManager.GetString("Compiler_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output compressed {0}, compression ratio: {1}%.
        /// </summary>
        internal static string Compress_Info {
            get {
                return ResourceManager.GetString("Compress_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution context initialized for connection {0} client {1} session {2}.
        /// </summary>
        internal static string Context_Initialized {
            get {
                return ResourceManager.GetString("Context_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution context is missing.
        /// </summary>
        internal static string Context_MissingError {
            get {
                return ResourceManager.GetString("Context_MissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataDestination removing subscriber {0}.
        /// </summary>
        internal static string DataDestination_RemoveSubscriber {
            get {
                return ResourceManager.GetString("DataDestination_RemoveSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not handled by DotNetAdapter, operation = {0}.
        /// </summary>
        internal static string DataService_Unknown {
            get {
                return ResourceManager.GetString("DataService_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested destination &apos;{0}&apos; is not accessible.
        /// </summary>
        internal static string Destination_NotFound {
            get {
                return ResourceManager.GetString("Destination_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination &apos;{0}&apos;({1}) already initialized.
        /// </summary>
        internal static string Destination_Reinit {
            get {
                return ResourceManager.GetString("Destination_Reinit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query endpoint endpointPath {0} contextPath {1}.
        /// </summary>
        internal static string Endpoint_Bind {
            get {
                return ResourceManager.GetString("Endpoint_Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not bind request to endpoint {0}, contextPath {1}.
        /// </summary>
        internal static string Endpoint_BindFail {
            get {
                return ResourceManager.GetString("Endpoint_BindFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} endpoint handling message {1}.
        /// </summary>
        internal static string Endpoint_HandleMessage {
            get {
                return ResourceManager.GetString("Endpoint_HandleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} endpoint routing response {1}.
        /// </summary>
        internal static string Endpoint_Response {
            get {
                return ResourceManager.GetString("Endpoint_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error context dump.
        /// </summary>
        internal static string Error_ContextDump {
            get {
                return ResourceManager.GetString("Error_ContextDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object of type {0} does not implement IExternalizable.
        /// </summary>
        internal static string Externalizable_CastFail {
            get {
                return ResourceManager.GetString("Externalizable_CastFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal problem detected {0}.
        /// </summary>
        internal static string Fluorine_Fatal {
            get {
                return ResourceManager.GetString("Fluorine_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize http module.
        /// </summary>
        internal static string Fluorine_InitModule {
            get {
                return ResourceManager.GetString("Fluorine_InitModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting FluorineFx Gateway.
        /// </summary>
        internal static string Fluorine_Start {
            get {
                return ResourceManager.GetString("Fluorine_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluorineFx version {0}.
        /// </summary>
        internal static string Fluorine_Version {
            get {
                return ResourceManager.GetString("Fluorine_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get identity failed, member {0}.
        /// </summary>
        internal static string Identity_Failed {
            get {
                return ResourceManager.GetString("Identity_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Destination &apos;{0}&apos;.
        /// </summary>
        internal static string Invalid_Destination {
            get {
                return ResourceManager.GetString("Invalid_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method ambiguity, could not select the method with name {0}.
        /// </summary>
        internal static string Invocation_Ambiguity {
            get {
                return ResourceManager.GetString("Invocation_Ambiguity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception has been thrown by the invoked method {0}: {1}.
        /// </summary>
        internal static string Invocation_Failed {
            get {
                return ResourceManager.GetString("Invocation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a suitable method with name {0}.
        /// </summary>
        internal static string Invocation_NoSuitableMethod {
            get {
                return ResourceManager.GetString("Invocation_NoSuitableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0}  received {1}.
        /// </summary>
        internal static string Invocation_ParameterType {
            get {
                return ResourceManager.GetString("Invocation_ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking method {0}.
        /// </summary>
        internal static string Invoke_Method {
            get {
                return ResourceManager.GetString("Invoke_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin JSON request.
        /// </summary>
        internal static string Json_Begin {
            get {
                return ResourceManager.GetString("Json_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End JSON request.
        /// </summary>
        internal static string Json_End {
            get {
                return ResourceManager.GetString("Json_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON request was not handled. Check your log file for further information.
        /// </summary>
        internal static string Json_Fatal {
            get {
                return ResourceManager.GetString("Json_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Failed to handle JSON request.
        /// </summary>
        internal static string Json_Fatal404 {
            get {
                return ResourceManager.GetString("Json_Fatal404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Broker is not accessible.
        /// </summary>
        internal static string MessageBroker_NotAvailable {
            get {
                return ResourceManager.GetString("MessageBroker_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error registering MessageBroker {0}.
        /// </summary>
        internal static string MessageBroker_RegisterError {
            get {
                return ResourceManager.GetString("MessageBroker_RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing response {0}.
        /// </summary>
        internal static string MessageBroker_Response {
            get {
                return ResourceManager.GetString("MessageBroker_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBroker routing message.
        /// </summary>
        internal static string MessageBroker_RoutingError {
            get {
                return ResourceManager.GetString("MessageBroker_RoutingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing message {0} .
        /// </summary>
        internal static string MessageBroker_RoutingMessage {
            get {
                return ResourceManager.GetString("MessageBroker_RoutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect MessageClient {0}.
        /// </summary>
        internal static string MessageClient_Disconnect {
            get {
                return ResourceManager.GetString("MessageClient_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout MessageClient {0}.
        /// </summary>
        internal static string MessageClient_Timeout {
            get {
                return ResourceManager.GetString("MessageClient_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe MessageClient {0}.
        /// </summary>
        internal static string MessageClient_Unsubscribe {
            get {
                return ResourceManager.GetString("MessageClient_Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageDestination removing subscriber {0}.
        /// </summary>
        internal static string MessageDestination_RemoveSubscriber {
            get {
                return ResourceManager.GetString("MessageDestination_RemoveSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access the Message Server.
        /// </summary>
        internal static string MessageServer_AccessFail {
            get {
                return ResourceManager.GetString("MessageServer_AccessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Message Server.
        /// </summary>
        internal static string MessageServer_Create {
            get {
                return ResourceManager.GetString("MessageServer_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a services configuration file, using default settings.
        /// </summary>
        internal static string MessageServer_LoadingConfigDefault {
            get {
                return ResourceManager.GetString("MessageServer_LoadingConfigDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading services configuration file from {0}.
        /// </summary>
        internal static string MessageServer_LoadingServiceConfig {
            get {
                return ResourceManager.GetString("MessageServer_LoadingServiceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination &apos;{0}&apos;({1}) initialized with invalid adapter.
        /// </summary>
        internal static string MessageServer_MissingAdapter {
            get {
                return ResourceManager.GetString("MessageServer_MissingAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Message Broker.
        /// </summary>
        internal static string MessageServer_Start {
            get {
                return ResourceManager.GetString("MessageServer_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Server started.
        /// </summary>
        internal static string MessageServer_Started {
            get {
                return ResourceManager.GetString("MessageServer_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Message Broker.
        /// </summary>
        internal static string MessageServer_StartError {
            get {
                return ResourceManager.GetString("MessageServer_StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Message Broker.
        /// </summary>
        internal static string MessageServer_Stop {
            get {
                return ResourceManager.GetString("MessageServer_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to load services configuration file from {0}.
        /// </summary>
        internal static string MessageServer_TryingServiceConfig {
            get {
                return ResourceManager.GetString("MessageServer_TryingServiceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push message {0} to client {1}.
        /// </summary>
        internal static string MessageServicePush {
            get {
                return ResourceManager.GetString("MessageServicePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push binary message {0} to client {1}.
        /// </summary>
        internal static string MessageServicePushBinary {
            get {
                return ResourceManager.GetString("MessageServicePushBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageService adapter servicing message for destination &apos;{0}&apos; from client {1}.
        /// </summary>
        internal static string MessageServiceRoute {
            get {
                return ResourceManager.GetString("MessageServiceRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageService servicing subscribe command for destination &apos;{0}&apos;, new message client {1}.
        /// </summary>
        internal static string MessageServiceSubscribe {
            get {
                return ResourceManager.GetString("MessageServiceSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageService servicing unknown command ({0}) for destination &apos;{1}&apos;.
        /// </summary>
        internal static string MessageServiceUnknown {
            get {
                return ResourceManager.GetString("MessageServiceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageService servicing unsubscribe command for destination &apos;{0}&apos;, client {1}.
        /// </summary>
        internal static string MessageServiceUnsubscribe {
            get {
                return ResourceManager.GetString("MessageServiceUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsmqAdapter change enabled state ({0}).
        /// </summary>
        internal static string Msmq_Enable {
            get {
                return ResourceManager.GetString("Msmq_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsmqAdapter failed.
        /// </summary>
        internal static string Msmq_Fail {
            get {
                return ResourceManager.GetString("Msmq_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsmqAdapter init formatter {0}.
        /// </summary>
        internal static string Msmq_InitFormatter {
            get {
                return ResourceManager.GetString("Msmq_InitFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsmqAdapter could not process message. Possible poison message.
        /// </summary>
        internal static string Msmq_Poison {
            get {
                return ResourceManager.GetString("Msmq_Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsmqAdapter received message, label = {0}, id = {1}.
        /// </summary>
        internal static string Msmq_Receive {
            get {
                return ResourceManager.GetString("Msmq_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsmqAdapter sending message for client {0}.
        /// </summary>
        internal static string Msmq_Send {
            get {
                return ResourceManager.GetString("Msmq_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsmqAdapter starting queue {0}.
        /// </summary>
        internal static string Msmq_StartQueue {
            get {
                return ResourceManager.GetString("Msmq_StartQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal reflection optimizer problem detected. Please turn off the reflection optimizer in the configuration file and check your log file for further information.
        /// </summary>
        internal static string Optimizer_Fatal {
            get {
                return ResourceManager.GetString("Optimizer_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom AMF deserializer source code for {0} located at {1}.
        /// </summary>
        internal static string Optimizer_FileLocation {
            get {
                return ResourceManager.GetString("Optimizer_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflection optimizer problem detected. Please turn off the reflection optimizer in the configuration file and check your log file for further information.
        /// </summary>
        internal static string Optimizer_Warning {
            get {
                return ResourceManager.GetString("Optimizer_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push not supported.
        /// </summary>
        internal static string PushNotSupported {
            get {
                return ResourceManager.GetString("PushNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} set failed. {1}.
        /// </summary>
        internal static string Reflection_FieldSetFail {
            get {
                return ResourceManager.GetString("Reflection_FieldSetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member {0} not found.
        /// </summary>
        internal static string Reflection_MemberNotFound {
            get {
                return ResourceManager.GetString("Reflection_MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index parameters are required for the property {0}. Use the [Transient] attribute to identify a property that should be omitted from data that is sent to the client.
        /// </summary>
        internal static string Reflection_PropertyIndexFail {
            get {
                return ResourceManager.GetString("Reflection_PropertyIndexFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write property {0}.
        /// </summary>
        internal static string Reflection_PropertyReadOnly {
            get {
                return ResourceManager.GetString("Reflection_PropertyReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} set failed. {1}.
        /// </summary>
        internal static string Reflection_PropertySetFail {
            get {
                return ResourceManager.GetString("Reflection_PropertySetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Begin disconnect.
        /// </summary>
        internal static string Rtmp_BeginDisconnect {
            get {
                return ResourceManager.GetString("Rtmp_BeginDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Start processing RTMP packet.
        /// </summary>
        internal static string Rtmp_BeginHandlePacket {
            get {
                return ResourceManager.GetString("Rtmp_BeginHandlePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk too small, buffering ({0},{1}).
        /// </summary>
        internal static string Rtmp_ChunkSmall {
            get {
                return ResourceManager.GetString("Rtmp_ChunkSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Closing connection.
        /// </summary>
        internal static string Rtmp_ConnectionClose {
            get {
                return ResourceManager.GetString("Rtmp_ConnectionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process message.
        /// </summary>
        internal static string Rtmp_CouldNotProcessMessage {
            get {
                return ResourceManager.GetString("Rtmp_CouldNotProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data, remaining {0} buffering {1}.
        /// </summary>
        internal static string Rtmp_DataBuffering {
            get {
                return ResourceManager.GetString("Rtmp_DataBuffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode header {0}.
        /// </summary>
        internal static string Rtmp_DecodeHeader {
            get {
                return ResourceManager.GetString("Rtmp_DecodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} End processing RTMP packet.
        /// </summary>
        internal static string Rtmp_EndHandlePacket {
            get {
                return ResourceManager.GetString("Rtmp_EndHandlePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTMP handler runtime error.
        /// </summary>
        internal static string Rtmp_HandlerError {
            get {
                return ResourceManager.GetString("Rtmp_HandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header too small, buffering. Remaining: {0}.
        /// </summary>
        internal static string Rtmp_HeaderBuffering {
            get {
                return ResourceManager.GetString("Rtmp_HeaderBuffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handshake init too small, buffering. Remaining: {0}.
        /// </summary>
        internal static string Rtmp_HSInitBuffering {
            get {
                return ResourceManager.GetString("Rtmp_HSInitBuffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handshake reply too small, buffering. Remaining: {0}.
        /// </summary>
        internal static string Rtmp_HSReplyBuffering {
            get {
                return ResourceManager.GetString("Rtmp_HSReplyBuffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add mapping {0} =&gt; {1}.
        /// </summary>
        internal static string Rtmp_ServerAddMapping {
            get {
                return ResourceManager.GetString("Rtmp_ServerAddMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove mapping {0}.
        /// </summary>
        internal static string Rtmp_ServerRemoveMapping {
            get {
                return ResourceManager.GetString("Rtmp_ServerRemoveMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Socket begin read callback.
        /// </summary>
        internal static string Rtmp_SocketBeginRead {
            get {
                return ResourceManager.GetString("Rtmp_SocketBeginRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Socket begin receive iocp = {1}.
        /// </summary>
        internal static string Rtmp_SocketBeginReceive {
            get {
                return ResourceManager.GetString("Rtmp_SocketBeginReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Socket begin send iocp = {1}.
        /// </summary>
        internal static string Rtmp_SocketBeginSend {
            get {
                return ResourceManager.GetString("Rtmp_SocketBeginSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} An established connection was aborted ({1}).
        /// </summary>
        internal static string Rtmp_SocketConnectionAborted {
            get {
                return ResourceManager.GetString("Rtmp_SocketConnectionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Connection reset by peer ({1}).
        /// </summary>
        internal static string Rtmp_SocketConnectionReset {
            get {
                return ResourceManager.GetString("Rtmp_SocketConnectionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ({1}).
        /// </summary>
        internal static string Rtmp_SocketConnectionTimeout {
            get {
                return ResourceManager.GetString("Rtmp_SocketConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Socket disconnect.
        /// </summary>
        internal static string Rtmp_SocketDisconnectProcessing {
            get {
                return ResourceManager.GetString("Rtmp_SocketDisconnectProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SocketListener accept.
        /// </summary>
        internal static string Rtmp_SocketListenerAccept {
            get {
                return ResourceManager.GetString("Rtmp_SocketListenerAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Socket read processing.
        /// </summary>
        internal static string Rtmp_SocketReadProcessing {
            get {
                return ResourceManager.GetString("Rtmp_SocketReadProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Socket receive processing.
        /// </summary>
        internal static string Rtmp_SocketReceiveProcessing {
            get {
                return ResourceManager.GetString("Rtmp_SocketReceiveProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Socket send.
        /// </summary>
        internal static string Rtmp_SocketSend {
            get {
                return ResourceManager.GetString("Rtmp_SocketSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Socket send processing.
        /// </summary>
        internal static string Rtmp_SocketSendProcessing {
            get {
                return ResourceManager.GetString("Rtmp_SocketSendProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Write {1}.
        /// </summary>
        internal static string Rtmp_WritePacket {
            get {
                return ResourceManager.GetString("Rtmp_WritePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtmpEndpoint error.
        /// </summary>
        internal static string RtmpEndpoint_Error {
            get {
                return ResourceManager.GetString("RtmpEndpoint_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RtmpEndpoint failed.
        /// </summary>
        internal static string RtmpEndpoint_Failed {
            get {
                return ResourceManager.GetString("RtmpEndpoint_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting RtmpEndpoint.
        /// </summary>
        internal static string RtmpEndpoint_Start {
            get {
                return ResourceManager.GetString("RtmpEndpoint_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started RtmpEndpoint.
        /// </summary>
        internal static string RtmpEndpoint_Started {
            get {
                return ResourceManager.GetString("RtmpEndpoint_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting server, listening on port {0}.
        /// </summary>
        internal static string RtmpEndpoint_Starting {
            get {
                return ResourceManager.GetString("RtmpEndpoint_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped RtmpEndpoint.
        /// </summary>
        internal static string RtmpEndpoint_Stopped {
            get {
                return ResourceManager.GetString("RtmpEndpoint_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping RtmpEndpoint.
        /// </summary>
        internal static string RtmpEndpoint_Stopping {
            get {
                return ResourceManager.GetString("RtmpEndpoint_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin RTMPT request.
        /// </summary>
        internal static string Rtmpt_Begin {
            get {
                return ResourceManager.GetString("Rtmpt_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request, only RTMPT supported.
        /// </summary>
        internal static string Rtmpt_CommandBadRequest {
            get {
                return ResourceManager.GetString("Rtmpt_CommandBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing close command {0}.
        /// </summary>
        internal static string Rtmpt_CommandClose {
            get {
                return ResourceManager.GetString("Rtmpt_CommandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing idle command {0}.
        /// </summary>
        internal static string Rtmpt_CommandIdle {
            get {
                return ResourceManager.GetString("Rtmpt_CommandIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTMPT command {0} is not supported.
        /// </summary>
        internal static string Rtmpt_CommandNotSupported {
            get {
                return ResourceManager.GetString("Rtmpt_CommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing open command {0}.
        /// </summary>
        internal static string Rtmpt_CommandOpen {
            get {
                return ResourceManager.GetString("Rtmpt_CommandOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing send command {0}.
        /// </summary>
        internal static string Rtmpt_CommandSend {
            get {
                return ResourceManager.GetString("Rtmpt_CommandSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End RTMPT request.
        /// </summary>
        internal static string Rtmpt_End {
            get {
                return ResourceManager.GetString("Rtmpt_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTMPT message was not handled. Check your log file for further information.
        /// </summary>
        internal static string Rtmpt_Fatal {
            get {
                return ResourceManager.GetString("Rtmpt_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Failed to handle RTMPT. Check your log file for further information.
        /// </summary>
        internal static string Rtmpt_Fatal404 {
            get {
                return ResourceManager.GetString("Rtmpt_Fatal404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not notify stream subsystem about sent message.
        /// </summary>
        internal static string Rtmpt_NotifyError {
            get {
                return ResourceManager.GetString("Rtmpt_NotifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning {0} pending messages to client.
        /// </summary>
        internal static string Rtmpt_ReturningMessages {
            get {
                return ResourceManager.GetString("Rtmpt_ReturningMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown client {0}.
        /// </summary>
        internal static string Rtmpt_UnknownClient {
            get {
                return ResourceManager.GetString("Rtmpt_UnknownClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check {0}.
        /// </summary>
        internal static string Scope_Check {
            get {
                return ResourceManager.GetString("Scope_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check default host, default path {0}.
        /// </summary>
        internal static string Scope_CheckDefaultHostPath {
            get {
                return ResourceManager.GetString("Scope_CheckDefaultHostPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check host with no path {0}.
        /// </summary>
        internal static string Scope_CheckHostNoPath {
            get {
                return ResourceManager.GetString("Scope_CheckHostNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check host and path {0}.
        /// </summary>
        internal static string Scope_CheckHostPath {
            get {
                return ResourceManager.GetString("Scope_CheckHostPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check wildcard host with path {0}.
        /// </summary>
        internal static string Scope_CheckWildcardHostPath {
            get {
                return ResourceManager.GetString("Scope_CheckWildcardHostPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope {0} not found in {1}.
        /// </summary>
        internal static string Scope_ChildNotFound {
            get {
                return ResourceManager.GetString("Scope_ChildNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to scope {0}.
        /// </summary>
        internal static string Scope_Connect {
            get {
                return ResourceManager.GetString("Scope_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while disconnecting from scope {0}.
        /// </summary>
        internal static string Scope_DisconnectError {
            get {
                return ResourceManager.GetString("Scope_DisconnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect failed, scope not found. Path was {0}.
        /// </summary>
        internal static string Scope_NotFound {
            get {
                return ResourceManager.GetString("Scope_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while unregistering basic scopes.
        /// </summary>
        internal static string Scope_UnregisterError {
            get {
                return ResourceManager.GetString("Scope_UnregisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested access is not allowed.
        /// </summary>
        internal static string Security_AccessNotAllowed {
            get {
                return ResourceManager.GetString("Security_AccessNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate method must return a valid Principal object.
        /// </summary>
        internal static string Security_AuthenticationFailed {
            get {
                return ResourceManager.GetString("Security_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityConstraint reference \&quot;{0}\&quot; not found. Check services-config.xml. Security information for the current request was not available.
        /// </summary>
        internal static string Security_ConstraintRefNotFound {
            get {
                return ResourceManager.GetString("Security_ConstraintRefNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;security&gt; or &lt;security-constraint&gt; section not found. Check services-config.xml. Security information for the current request was not available.
        /// </summary>
        internal static string Security_ConstraintSectionNotFound {
            get {
                return ResourceManager.GetString("Security_ConstraintSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginCommand required. Please check your security configuration.
        /// </summary>
        internal static string Security_LoginMissing {
            get {
                return ResourceManager.GetString("Security_LoginMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector expression should evaluate to a boolean value.
        /// </summary>
        internal static string Selector_InvalidResult {
            get {
                return ResourceManager.GetString("Selector_InvalidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding subscriber {0} to sequence {1}.
        /// </summary>
        internal static string Sequence_AddSubscriber {
            get {
                return ResourceManager.GetString("Sequence_AddSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing subscriber {0} from sequence {1}.
        /// </summary>
        internal static string Sequence_RemoveSubscriber {
            get {
                return ResourceManager.GetString("Sequence_RemoveSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created sequence {0} client {1}.
        /// </summary>
        internal static string SequenceManager_CreateSeq {
            get {
                return ResourceManager.GetString("SequenceManager_CreateSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseCollection sequence {0} client {1}.
        /// </summary>
        internal static string SequenceManager_ReleaseCollection {
            get {
                return ResourceManager.GetString("SequenceManager_ReleaseCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing sequence {0}.
        /// </summary>
        internal static string SequenceManager_Remove {
            get {
                return ResourceManager.GetString("SequenceManager_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing sequence {0} all clients disconnected.
        /// </summary>
        internal static string SequenceManager_RemoveEmptySeq {
            get {
                return ResourceManager.GetString("SequenceManager_RemoveEmptySeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataDestination &apos;{0}&apos; {1} sequences left.
        /// </summary>
        internal static string SequenceManager_RemoveStatus {
            get {
                return ResourceManager.GetString("SequenceManager_RemoveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceManager removing subscriber {0}.
        /// </summary>
        internal static string SequenceManager_RemoveSubscriber {
            get {
                return ResourceManager.GetString("SequenceManager_RemoveSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceManager removing subscriber {0} from sequence {1}.
        /// </summary>
        internal static string SequenceManager_RemoveSubscriberSeq {
            get {
                return ResourceManager.GetString("SequenceManager_RemoveSubscriberSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageSequence: message was not handled. Operation = {0}.
        /// </summary>
        internal static string SequenceManager_Unknown {
            get {
                return ResourceManager.GetString("SequenceManager_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping service name {0} to {1}.
        /// </summary>
        internal static string Service_Mapping {
            get {
                return ResourceManager.GetString("Service_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} not found.
        /// </summary>
        internal static string Service_NotFound {
            get {
                return ResourceManager.GetString("Service_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; failed routing message for destination &apos;{1}&apos;, the message was: {2}.
        /// </summary>
        internal static string ServiceAdapter_ManageFail {
            get {
                return ResourceManager.GetString("ServiceAdapter_ManageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find settings for service adapter.
        /// </summary>
        internal static string ServiceAdapter_MissingSettings {
            get {
                return ResourceManager.GetString("ServiceAdapter_MissingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service adapter.
        /// </summary>
        internal static string ServiceAdapter_Stop {
            get {
                return ResourceManager.GetString("ServiceAdapter_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquire ServiceBrowser renderer.
        /// </summary>
        internal static string ServiceBrowser_Aquire {
            get {
                return ResourceManager.GetString("ServiceBrowser_Aquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquired ServiceBrowser renderer.
        /// </summary>
        internal static string ServiceBrowser_Aquired {
            get {
                return ResourceManager.GetString("ServiceBrowser_Aquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to aquire ServiceBrowser renderer.
        /// </summary>
        internal static string ServiceBrowser_AquireFail {
            get {
                return ResourceManager.GetString("ServiceBrowser_AquireFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while invoking method &apos;{0}&apos; on service handler object &apos;{1}&apos;.
        /// </summary>
        internal static string ServiceHandler_InvocationFailed {
            get {
                return ResourceManager.GetString("ServiceHandler_InvocationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested service {0} found {1} in scope {2}.
        /// </summary>
        internal static string ServiceInvoker_Resolve {
            get {
                return ResourceManager.GetString("ServiceInvoker_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested service {0} was not found  in scope {1}.
        /// </summary>
        internal static string ServiceInvoker_ResolveFail {
            get {
                return ResourceManager.GetString("ServiceInvoker_ResolveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new session with id {0}.
        /// </summary>
        internal static string Session_Create {
            get {
                return ResourceManager.GetString("Session_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session with id {0} has been invalidated.
        /// </summary>
        internal static string Session_Invalidated {
            get {
                return ResourceManager.GetString("Session_Invalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session with id {0} changing lease time from {1} to {2}.
        /// </summary>
        internal static string Session_Lease {
            get {
                return ResourceManager.GetString("Session_Lease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionManager cache expired, session with id {0}.
        /// </summary>
        internal static string SessionManager_CacheExpired {
            get {
                return ResourceManager.GetString("SessionManager_CacheExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionManager removing session with id {0}.
        /// </summary>
        internal static string SessionManager_Remove {
            get {
                return ResourceManager.GetString("SessionManager_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting shared object {0} all clients disconnected.
        /// </summary>
        internal static string SharedObject_Delete {
            get {
                return ResourceManager.GetString("SharedObject_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove shared object.
        /// </summary>
        internal static string SharedObject_DeleteError {
            get {
                return ResourceManager.GetString("SharedObject_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not store shared object.
        /// </summary>
        internal static string SharedObject_StoreError {
            get {
                return ResourceManager.GetString("SharedObject_StoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send shared object sync message to {0}.
        /// </summary>
        internal static string SharedObject_Sync {
            get {
                return ResourceManager.GetString("SharedObject_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send sync message to unknown connection.
        /// </summary>
        internal static string SharedObject_SyncConnError {
            get {
                return ResourceManager.GetString("SharedObject_SyncConnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created persistence store {0} for shared objects.
        /// </summary>
        internal static string SharedObjectService_CreateStore {
            get {
                return ResourceManager.GetString("SharedObjectService_CreateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create persistence store for shared objects, falling back to memory persistence.
        /// </summary>
        internal static string SharedObjectService_CreateStoreError {
            get {
                return ResourceManager.GetString("SharedObjectService_CreateStoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight policy server error.
        /// </summary>
        internal static string Silverlight_PSError {
            get {
                return ResourceManager.GetString("Silverlight_PSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Silverlight policy server, policy file: {0}.
        /// </summary>
        internal static string Silverlight_StartPS {
            get {
                return ResourceManager.GetString("Silverlight_StartPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocketServer Failed.
        /// </summary>
        internal static string SocketServer_Failed {
            get {
                return ResourceManager.GetString("SocketServer_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket listener failed.
        /// </summary>
        internal static string SocketServer_ListenerFail {
            get {
                return ResourceManager.GetString("SocketServer_ListenerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSocketOption {0} failed.
        /// </summary>
        internal static string SocketServer_SocketOptionFail {
            get {
                return ResourceManager.GetString("SocketServer_SocketOptionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting SocketServer.
        /// </summary>
        internal static string SocketServer_Start {
            get {
                return ResourceManager.GetString("SocketServer_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started SocketServer.
        /// </summary>
        internal static string SocketServer_Started {
            get {
                return ResourceManager.GetString("SocketServer_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped SocketServer.
        /// </summary>
        internal static string SocketServer_Stopped {
            get {
                return ResourceManager.GetString("SocketServer_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping SocketServer.
        /// </summary>
        internal static string SocketServer_Stopping {
            get {
                return ResourceManager.GetString("SocketServer_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionManager cache expired, subscriber with id {0}.
        /// </summary>
        internal static string SubscriptionManager_CacheExpired {
            get {
                return ResourceManager.GetString("SubscriptionManager_CacheExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionManager removing subscriber with id {0}.
        /// </summary>
        internal static string SubscriptionManager_Remove {
            get {
                return ResourceManager.GetString("SubscriptionManager_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subtopic {0}.
        /// </summary>
        internal static string Subtopic_Invalid {
            get {
                return ResourceManager.GetString("Subtopic_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin SWX request.
        /// </summary>
        internal static string Swx_Begin {
            get {
                return ResourceManager.GetString("Swx_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End SWX request.
        /// </summary>
        internal static string Swx_End {
            get {
                return ResourceManager.GetString("Swx_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swx request was not handled. Check your log file for further information.
        /// </summary>
        internal static string Swx_Fatal {
            get {
                return ResourceManager.GetString("Swx_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Failed to handle SWX request.
        /// </summary>
        internal static string Swx_Fatal404 {
            get {
                return ResourceManager.GetString("Swx_Fatal404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is not valid. Cross-domain access will not work. {0}.
        /// </summary>
        internal static string Swx_InvalidCrossDomainUrl {
            get {
                return ResourceManager.GetString("Swx_InvalidCrossDomainUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate the requested  type {0}.
        /// </summary>
        internal static string Type_InitError {
            get {
                return ResourceManager.GetString("Type_InitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The received RPC source does not meet the destination source specification..
        /// </summary>
        internal static string Type_Mismatch {
            get {
                return ResourceManager.GetString("Type_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The received RPC source {0} does not meet the destination source specification {1}. A Destination with asterisk(*) requires that the source be set properly by the Flex client..
        /// </summary>
        internal static string Type_MismatchMissingSource {
            get {
                return ResourceManager.GetString("Type_MismatchMissingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type conversion failed.
        /// </summary>
        internal static string TypeHelper_ConversionFail {
            get {
                return ResourceManager.GetString("TypeHelper_ConversionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load dynamic link library {0} from LAC.
        /// </summary>
        internal static string TypeHelper_LoadDllFail {
            get {
                return ResourceManager.GetString("TypeHelper_LoadDllFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeHelper probing assembly {0} for type &apos;{1}&apos;.
        /// </summary>
        internal static string TypeHelper_Probing {
            get {
                return ResourceManager.GetString("TypeHelper_Probing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type identifier {0} loaded.
        /// </summary>
        internal static string TypeIdentifier_Loaded {
            get {
                return ResourceManager.GetString("TypeIdentifier_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} could not be loaded. Using ActionScript typed object (ASObject).
        /// </summary>
        internal static string TypeLoad_ASO {
            get {
                return ResourceManager.GetString("TypeLoad_ASO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write custom object {0} mapping to {1}.
        /// </summary>
        internal static string TypeMapping_Write {
            get {
                return ResourceManager.GetString("TypeMapping_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find serializer for type {0}.
        /// </summary>
        internal static string TypeSerializer_NotFound {
            get {
                return ResourceManager.GetString("TypeSerializer_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating a proxy assembly for the web service {0}.
        /// </summary>
        internal static string Wsdl_ProxyGen {
            get {
                return ResourceManager.GetString("Wsdl_ProxyGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy generation failed.
        /// </summary>
        internal static string Wsdl_ProxyGenFail {
            get {
                return ResourceManager.GetString("Wsdl_ProxyGenFail", resourceCulture);
            }
        }
    }
}
